import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// Spike app. Data lives in public/data (a copy of ../web/data, regenerated by the
// Python pipeline). Runs fully self-contained on port 5174.
export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: { port: 5174 },
})
